using System;
using System.IO;
using UnityEngine;

/// <summary>
/// Loads SRTM RAW heightmap files generated by srtm_download.py.
/// Provides per-point elevation sampling for TerrainMesher and OsmParser.
/// Singleton — access via SRTMHeightmap.Instance.
/// Must be initialized before WorldStreamer starts loading chunks.
/// </summary>
public class SRTMHeightmap : MonoBehaviour
{
    public static SRTMHeightmap Instance { get; private set; }

    [Header("Files (relative to StreamingAssets/SRTM/)")]
    public string MetadataFile = "akure_srtm_meta.json";
    public string LOD0File     = "akure_srtm_lod0.raw"; // 129x129
    public string LOD1File     = "akure_srtm_lod1.raw"; // 65x65
    public string LOD2File     = "akure_srtm_lod2.raw"; // 33x33

    [Header("LOD Switch Distances (meters)")]
    public float LOD1Distance = 2000f;
    public float LOD2Distance = 4000f;

    // Metadata
    public float MinElevation  { get; private set; }
    public float MaxElevation  { get; private set; }
    public float ElevRange     { get; private set; }
    public float BaseElevation { get; private set; }
    public bool  IsLoaded      { get; private set; }

    // Geographic bounds
    private float _minLat, _maxLat, _minLon, _maxLon;

    // Heightmap grids per LOD — normalized 0-1 values
    private float[,] _lod0; // 129x129
    private float[,] _lod1; // 65x65
    private float[,] _lod2; // 33x33
    private int[]    _lodSizes;

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }
        Instance = this;
        DontDestroyOnLoad(gameObject);

        LoadHeightmaps();
    }

    /// <summary>
    /// Returns elevation in meters at a given world XZ position.
    /// Uses LOD0 (highest detail) by default.
    /// </summary>
    public float GetElevation(float worldX, float worldZ)
    {
        return SampleGrid(_lod0, _lodSizes[0], worldX, worldZ);
    }

    /// <summary>
    /// Returns elevation using the appropriate LOD based on distance from player.
    /// </summary>
    public float GetElevationLOD(float worldX, float worldZ, float distanceFromPlayer)
    {
        if (distanceFromPlayer > LOD2Distance)
            return SampleGrid(_lod2, _lodSizes[2], worldX, worldZ);
        if (distanceFromPlayer > LOD1Distance)
            return SampleGrid(_lod1, _lodSizes[1], worldX, worldZ);
        return SampleGrid(_lod0, _lodSizes[0], worldX, worldZ);
    }

    /// <summary>
    /// Samples a grid of elevation values for a chunk.
    /// Returns float[gridSize, gridSize] array of world Y values.
    /// Used by TerrainMesher to build chunk meshes.
    /// </summary>
    public float[,] SampleChunkGrid(ChunkBounds chunk, int gridSize, float distanceFromPlayer)
    {
        float[,] grid    = distanceFromPlayer > LOD2Distance ? _lod2 :
                           distanceFromPlayer > LOD1Distance ? _lod1 : _lod0;
        int      lodSize = distanceFromPlayer > LOD2Distance ? _lodSizes[2] :
                           distanceFromPlayer > LOD1Distance ? _lodSizes[1] : _lodSizes[0];

        var result = new float[gridSize, gridSize];

        for (int row = 0; row < gridSize; row++)
        {
            for (int col = 0; col < gridSize; col++)
            {
                float worldX = Mathf.Lerp(chunk.WorldMin.x, chunk.WorldMax.x,
                                          col / (float)(gridSize - 1));
                float worldZ = Mathf.Lerp(chunk.WorldMin.y, chunk.WorldMax.y,
                                          row / (float)(gridSize - 1));

                result[row, col] = SampleGrid(grid, lodSize, worldX, worldZ);
            }
        }

        return result;
    }

    /// <summary>
    /// Returns the raw heightmap grid and its world coverage for a given LOD.
    /// Used by TerrainMesher to do gap-free border vertex sampling.
    /// </summary>
    public void GetLODInfo(
        float        distanceFromPlayer,
        out float[,] heightGrid,
        out int      lodSize,
        out float    gridWorldMinX,
        out float    gridWorldMinZ,
        out float    gridWorldWidth,
        out float    gridWorldLength)
    {
        if (distanceFromPlayer > LOD2Distance)
        { heightGrid = _lod2; lodSize = _lodSizes[2]; }
        else if (distanceFromPlayer > LOD1Distance)
        { heightGrid = _lod1; lodSize = _lodSizes[1]; }
        else
        { heightGrid = _lod0; lodSize = _lodSizes[0]; }

        float mpdLon = Mercator.MetersPerDegreeLon();
        float mpdLat = Mercator.MetersPerDegreeLat();

        gridWorldMinX   = (_minLon - (float)Mercator.OriginLon) * mpdLon;
        gridWorldMinZ   = (_minLat - (float)Mercator.OriginLat) * mpdLat;
        gridWorldWidth  = (_maxLon - _minLon) * mpdLon;
        gridWorldLength = (_maxLat - _minLat) * mpdLat;
    }

    /// <summary>
    /// Editor-only: loads SRTM data directly from byte arrays instead of file paths.
    /// Called by ChunkBaker so it can work without entering Play mode.
    /// </summary>
    public void LoadFromBytes(string metaJson, byte[] lod0Bytes, byte[] lod1Bytes, byte[] lod2Bytes)
    {
        try
        {
            var meta      = JsonUtility.FromJson<SRTMMetadata>(metaJson);
            MinElevation  = (float)meta.min_elev;
            MaxElevation  = (float)meta.max_elev;
            ElevRange     = (float)meta.elev_range;
            BaseElevation = (float)meta.base_elevation;
            _minLat       = (float)meta.min_lat;
            _maxLat       = (float)meta.max_lat;
            _minLon       = (float)meta.min_lon;
            _maxLon       = (float)meta.max_lon;
            _lodSizes     = meta.lod_sizes ?? new int[] { 129, 65, 33 };

            _lod0 = ParseRaw(lod0Bytes, _lodSizes[0]);
            _lod1 = ParseRaw(lod1Bytes, _lodSizes[1]);
            _lod2 = ParseRaw(lod2Bytes, _lodSizes[2]);

            if (_lod0 == null || _lod1 == null || _lod2 == null)
            {
                Debug.LogError("[SRTMHeightmap] LoadFromBytes — one or more RAW buffers failed to parse");
                return;
            }

            // Register as singleton so TerrainMesher can find it
            if (Instance == null) Instance = this;

            IsLoaded = true;
            Debug.Log($"[SRTMHeightmap] LoadFromBytes ✓ — " +
                      $"{MinElevation:F0}m to {MaxElevation:F0}m | Range: {ElevRange:F0}m");
        }
        catch (System.Exception e)
        {
            Debug.LogError($"[SRTMHeightmap] LoadFromBytes failed: {e.Message}");
        }
    }

    private float[,] ParseRaw(byte[] raw, int size)
    {
        int expected = size * size * 2;
        if (raw == null || raw.Length < expected)
        {
            Debug.LogError($"[SRTMHeightmap] RAW buffer too small: {raw?.Length} < {expected}");
            return null;
        }

        float[,] grid = new float[size, size];
        int      idx  = 0;
        for (int row = 0; row < size; row++)
            for (int col = 0; col < size; col++)
            {
                ushort val = (ushort)((raw[idx] << 8) | raw[idx + 1]);
                grid[row, col] = val / 65535f;
                idx += 2;
            }
        return grid;
    }

    // -----------------------------------------------------------------------
    // Private
    // -----------------------------------------------------------------------

    private void LoadHeightmaps()
    {
        string srtmDir = Path.Combine(Application.streamingAssetsPath, "SRTM");

        // Load metadata
        string metaPath = Path.Combine(srtmDir, MetadataFile);
        if (!File.Exists(metaPath))
        {
            Debug.LogError($"[SRTMHeightmap] Metadata not found: {metaPath}");
            Debug.LogError("[SRTMHeightmap] Run srtm_download.py and copy output to StreamingAssets/SRTM/");
            return;
        }

        try
        {
            var meta = JsonUtility.FromJson<SRTMMetadata>(File.ReadAllText(metaPath));

            MinElevation  = (float)meta.min_elev;
            MaxElevation  = (float)meta.max_elev;
            ElevRange     = (float)meta.elev_range;
            BaseElevation = (float)meta.base_elevation;
            _minLat       = (float)meta.min_lat;
            _maxLat       = (float)meta.max_lat;
            _minLon       = (float)meta.min_lon;
            _maxLon       = (float)meta.max_lon;
            _lodSizes     = meta.lod_sizes ?? new int[] { 129, 65, 33 };

            Debug.Log($"[SRTMHeightmap] Metadata loaded — " +
                      $"Elevation: {MinElevation:F0}m — {MaxElevation:F0}m | " +
                      $"Range: {ElevRange:F0}m");
        }
        catch (Exception e)
        {
            Debug.LogError($"[SRTMHeightmap] Failed to parse metadata: {e.Message}");
            return;
        }

        // Load RAW files
        string lod0Path = Path.Combine(srtmDir, LOD0File);
        string lod1Path = Path.Combine(srtmDir, LOD1File);
        string lod2Path = Path.Combine(srtmDir, LOD2File);

        _lod0 = ReadRaw(lod0Path, _lodSizes[0]);
        _lod1 = ReadRaw(lod1Path, _lodSizes[1]);
        _lod2 = ReadRaw(lod2Path, _lodSizes[2]);

        if (_lod0 == null || _lod1 == null || _lod2 == null)
        {
            Debug.LogError("[SRTMHeightmap] Failed to load one or more RAW files.");
            return;
        }

        IsLoaded = true;
        Debug.Log($"[SRTMHeightmap] All LOD heightmaps loaded successfully. " +
                  $"Base elevation: {BaseElevation:F1}m");
    }

    private float[,] ReadRaw(string path, int size)
    {
        if (!File.Exists(path))
        {
            Debug.LogError($"[SRTMHeightmap] RAW file not found: {path}");
            return null;
        }

        byte[]   raw    = File.ReadAllBytes(path);
        int      expect = size * size * 2;

        if (raw.Length < expect)
        {
            Debug.LogError($"[SRTMHeightmap] RAW file too small: {raw.Length} < {expect}");
            return null;
        }

        float[,] grid = new float[size, size];
        int      idx  = 0;

        for (int row = 0; row < size; row++)
        {
            for (int col = 0; col < size; col++)
            {
                ushort val = (ushort)((raw[idx] << 8) | raw[idx + 1]);
                grid[row, col] = val / 65535f;
                idx += 2;
            }
        }

        Debug.Log($"[SRTMHeightmap] Loaded {size}x{size} from {Path.GetFileName(path)}");
        return grid;
    }

    private float SampleGrid(float[,] grid, int lodSize, float worldX, float worldZ)
    {
        if (grid == null || !IsLoaded) return 0f;

        // Convert world XZ to normalized UV in terrain bounds
        float mpdLon = Mercator.MetersPerDegreeLon();
        float mpdLat = Mercator.MetersPerDegreeLat();

        float terrainWidth  = (_maxLon - _minLon) * mpdLon;
        float terrainLength = (_maxLat - _minLat) * mpdLat;

        // Terrain bottom-left corner in world space
        float terrainOriginX = (_minLon - (float)Mercator.OriginLon) * mpdLon;
        float terrainOriginZ = (_minLat - (float)Mercator.OriginLat) * mpdLat;

        float u = (worldX - terrainOriginX) / terrainWidth;
        float v = (worldZ - terrainOriginZ) / terrainLength;

        u = Mathf.Clamp01(u);
        v = Mathf.Clamp01(v);

        // Bilinear interpolation
        float col = u * (lodSize - 1);
        float row = v * (lodSize - 1);

        int col0 = Mathf.Clamp(Mathf.FloorToInt(col), 0, lodSize - 2);
        int col1 = col0 + 1;
        int row0 = Mathf.Clamp(Mathf.FloorToInt(row), 0, lodSize - 2);
        int row1 = row0 + 1;

        float tc = col - col0;
        float tr = row - row0;

        float v00 = grid[row0, col0];
        float v10 = grid[row0, col1];
        float v01 = grid[row1, col0];
        float v11 = grid[row1, col1];

        float normalized = Mathf.Lerp(
            Mathf.Lerp(v00, v10, tc),
            Mathf.Lerp(v01, v11, tc),
            tr
        );

        // Convert normalized to world Y (meters above base elevation)
        return normalized * ElevRange;
    }
}

[Serializable]
public class SRTMMetadata
{
    public int[]  lod_sizes;
    public double min_elev;
    public double max_elev;
    public double elev_range;
    public double base_elevation;
    public double min_lat;
    public double max_lat;
    public double min_lon;
    public double max_lon;
    public double origin_lat;
    public double origin_lon;
    public double terrain_width;
    public double terrain_length;
    public double terrain_height;
}
